service: ts-aws-nodejs14
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
